lang = {
    'save':{ en : 'Save', th :'บันทึก' },
    'test':{ en :'test', th :'ทดสอบ'},
    'requirement':{ en :'Requirement', th :'คำร้องขอ'},
    'add_requirement':{ en :'Add Requirement', th :'เพิ่มคำร้องขอ'},
    'no':{ en :'NO', th :'ลำดับ'},
    'program_name':{ en :'Program Name', th :'ชื่อโปรแกรม'},
    'version':{ en :'Version', th :'เวอร์ชัน'},
    'company':{ en :'Company', th :'บริษัท'},
    'phone_number':{ en :'Phone Number', th :'เบอร์โทรศัพท์'},
    'responsible_person_project':{ en :'Responsible Person Project', th :'ผู้รับผิดชอบโครงการ'},
    'employee_code':{ en :'Employee Code', th :'รหัสพนักงาน'},
    'department':{ en :'Department', th :'ฝ่าย'},
    'division':{ en :'Division', th :'แผนก'},
    'want':{ en :'Want', th :'ความประสงค์'},
    'detail':{ en :'Detail', th :'รายละเอียด'},
    'document':{ en :'Document', th :'เอกสารแนบ'},
    'application_form':{ en :'Application Form For Improvement And Development', th :'แบบเสนอขอปรับปรุงและพัฒนาโปรแกรม'},
    'date_of_notification':{ en :'Date of notification', th :'วันที่แจ้ง'},
    'customer_name':{ en :'Customer Name', th :'ชื่อ-สกุลลูกค้า'},
    'customer_data':{ en :'Customer Data', th :'ข้อมูลลูกค้า'},
    'responsible_person_data':{ en :'Responsible Person Data', th :'ข้อมูลผู้รับผิดชอบ'},
    'employee_name':{ en :'Employee Name', th :'ชื่อพนักงาน'},
    'employee':{ en :'Employee', th :'พนักงาน'},
    'save':{ en :'Save', th :'บันทึก'},
    'cancel':{ en :'Cancel', th :'ยกเลิก'},
    'approve':{ en :'Approve', th :'อนุมัติ'},
    'not_approve':{ en :'Not Approve', th :'ไม่อนุมัติ'},
    'date':{ en :'Date', th :'วัน'},
    'baht':{ en :'Baht', th :'บาท'},
    'number_of_day':{ en :'Number Of Day', th :'จำนวนวันที่ใช้'},
    'estimated_cost':{ en :'Estimated Cost', th :'ประมาณการค่าใช้จ่าย'},
    'software_manager':{ en :'Software Manager', th :'ผู้จัดการแผนกพัฒนาซอฟต์แวร์'},
    'director_of_technology':{ en :'Director Of Technology', th :'ผู้อำนวยการฝ่ายเทคโนโลยี'},
    'status':{ en :'Status', th :'สถานะ'},
    'manage':{ en :'Manage', th :'จัดการ'},
    'edit':{ en :'Edit', th :'แก้ไข'},
    'delete':{ en :'Delete', th :'ลบ'},
    'part_of':{ en :'Part Of', th :'ส่วนของ'},
    'data':{ en :'Data', th :'ข้อมูล'},
    'import_development':{ en :'Task', th :'งาน'},
    'task':{ en :'Task', th :'งาน'},
    'date_of_import_development':{ en :'Date Of Import Development', th :'วันที่นำเข้าพัฒนา'},
    'expect_start_date':{ en :'Expect Start Date', th :'วันที่คาดว่าจะเริ่ม'},
    'expect_end_date':{ en :'Expect End Date', th :'วันที่คาดว่าสิ้นสุด'},
    'start_date':{ en :'Start Date', th :'วันที่เริ่ม'},
    'end_date':{ en :'End Date', th :'วันที่สิ้นสุด'},
    'deadline':{ en :'Deadline', th :'วันที่ต้องส่งงาน'},
    'sub_task':{ en :'Sub Task', th :'งานย่อย'},
    'primary_responsibility':{ en :'Primary Responsibility', th :'ผู้รับผิดชอบหลัก'},
    'expect_cost':{ en :'Expect Cost', th :'คาดว่าใช้ต้นทุน'},
    'expect_date':{ en :'Expect Date', th :'คาดว่าใช้เวลา'},
    'priority':{ en :'Priority', th :'ความสำคัญ'},
    'difficulty_level':{ en :'Difficulty level', th :'ระดับความยาก'},
    'basic_data':{ en :'Basic Data', th :'ข้อมูลพื้นฐานระบบ'},
    'add_department':{en :'Add Department',th :'เพิ่มฝ่าย'},
    'edit_department':{en :'Edit Department',th :'แก้ไขฝ่าย'},
    'add_division':{en :'Add Division',th :'เพิ่มแผนก'}, 
    'edit_division':{en :'Edit Division',th :'แก้ไขแผนก'}, 
    'plan':{en :'Plan',th :'แผน'}, 
    'plan2':{en :'Planning',th :'วางแผน'}, 
    'responsible_person':{ en :'Responsible Person', th :'ผู้รับผิดชอบ'},
    'cost':{ en :'Cost', th :'ค่าใช้จ่าย'},
    'previous_work':{ en :'Previous Work', th :'งานที่ต้องทำก่อน'},
    'work_schedule':{ en :'Work Schedule', th :'ตารางงาน'},
    'planning_information':{ en :'Planning Information', th :'ข้อมูลการวางแผน'},
    'view':{ en :'View', th :'ดู'},
    'company_namecustomer':{en :'Company Name (Customer)',th :'ชื่อบริษัท (ลูกค้า)'},
    'add_companycustomer':{en :'Add Company (Customer)',th :'เพิ่มบริษัท (ลูกค้า)'},
    'edit_companycustomer':{en :'Edit Company (Customer)',th :'แก้ไขบริษัท (ลูกค้า)'},
    'address':{en :'Address',th :'ที่อยู่'},
    'email':{en :'Email',th :'อีเมล'},
    'customer_name1':{en:'Name (Customer)',th:'ชื่อ (ลูกค้า)'},
    'customer_fname':{en : 'First Name (Customer)',th :'ชื่อ (ลูกค้า)'},
    'customer_lname':{en :'Last name (Customer)',th :'นามสกุล (ลูกค้า)'},
    'business_type':{en :'Business type',th :'ประเภทธุรกิจ'},
    'add_business_type':{en :'Add Business type',th:'เพิ่มประเภทธุรกิจ'},
    'edit_business_type':{en :'Edit Business type',th:'แก้ไขประเภทธุรกิจ'},
    'fname' :{en:'First Name',th :'ชื่อ'},
    'lname' :{en:'Last Name',th :'นามสกุล'},
    'position' :{en:'Position',th :'ตำแหน่ง'},
    'add_employeedata':{en:'Add Employeedata data',th:'เพิ่มข้อมูลพนักงาน'},
    'edit_employeedata':{en:'Edit Employeedata data',th:'แก้ไขข้อมูลพนักงาน'},
    'meeting':{en:'Meeting',th:'ประชุม'},
    'meetingshow':{en:'Meeting',th:'รายการประชุม'},
    'add_meeting':{en:'Add Meeting',th:'เพิ่มการประชุม'},
    'edit_meeting':{en:'Edit Meeting',th:'แก้ไขการประชุม'},
    'conference_topics':{en:'Conference topics',th:'หัวข้อการประชุม'},
    'episode':{en:'Episode',th:'ครั้งที่'},
    'meeting_date':{en:'Meeting Date',th:'วันที่ประชุม'},
    'time_meeting':{en:'Time',th:'เวลาประชุม'},
    'start_time':{en:'Start time',th:'เวลาที่เริ่มการประชุม'},
    'end_of_meeting':{en:'End of Meeting',th:'เวลาที่สิ้นสุดการประชุม'},
    'meeting_place' :{en:'Meeting place',th:'สถานที่ประชุม'},
    'meeting_details' :{en:'Meeting Details',th:'รายละเอียดการประชุม'},
    'recorder' :{en:'Recorder',th:'ผู้บันทึกการประชุม'},
    'develop' :{en:'Develop',th:'พัฒนา'},
    'add_develop' :{en:'Add Develop',th:'เพิ่มการพัฒนา'},
    'develop_tracking' :{en:'Development Tracking',th:'ติดตามการพัฒนา'},
    'progress' :{en:'Progress',th:'ความก้าวหน้า'},
    'complete' :{en:'Complete %',th:'ร้อยละงานที่เสร็จ'},
    'testing' :{en:'Testing', th:'การทดสอบ'},
    'test_the_time' :{en:'Testing the time',th:'ทดสอบครั้งที่'},
    'testing_date' :{en :'Testing date',th :'วันที่ทดสอบ'},
    'tester' :{en:'Tester',th:'ผู้ทดสอบ'},
    'add_testing':{en:'Add Testing',th:'เพิ่มการทดสอบ'},
    'edit_testing':{en:'Edit Testing',th:'แก้ไขการทดสอบ'},
    'add_position':{en: 'Add Position',th:'เพิ่มตำแหน่ง'},
    'edit_position':{en: 'Edit Position',th:'แก้ไขตำแหน่ง'},
    'warning':{en: 'Warning !',th:'คำเตือน !'},
    'pleas_enter_data':{en: 'Please Enter All Important Information.',th:'โปรดกรอกข้อมูลที่สำคัญให้ครบถ้วน'},
    'search_department':{en: 'Search Department',th:'ค้นหาฝ่าย'},
    'succrss':{en: 'Succrss',th:'สำเร็จ'},
    'add_succrss':{en: 'Added Successfully',th:'เพิ่มข้อมูลสำเร็จ'},
    'delete_succrss':{en: 'Delete Successfully',th:'ลบข้อมูลสำเร็จ'},
    'are_you_sure':{en: 'Are you sure ?',th:'ต้องการลบข้อมูลหรือไม่'},
    'if_delete':{en: 'If Deleted, Information Will Be Lost.',th:'หากลบแล้วข้อมูลจะหายไป'},
    'yes':{en: 'Yes',th:'ใช่'},
    'no_no':{en: 'No',th:'ไม่ใช่'},
    'search_business_type':{en: 'Search Business Type',th:'ค้นหาประเภทธุรกิจ'},
    'update_succrss':{en: 'Update Successfully',th:'แก้ไขข้อมูลสำเร็จ'},
    'search_division':{en: 'Search Division',th:'ค้นหาแผนก'},
    'search_position':{en: 'Search Position',th:'ค้นหาตำแหน่ง'},
    'username':{en: 'Username',th:'ชื่อผู้ใช้งาน'},
    'password':{en: 'Password',th:'รหัสผ่าน'},
    'serch_company':{en: 'Serch Company',th:'ค้นหาบริษัท'},
    'serch_employee':{en: 'Serch Employee',th:'ค้นหาพนักงาน'},
    'setting':{en: 'Setting',th:'ตั้งค่า'},
    'logout':{en: 'Logout',th:'ออกจากระบบ'},
    'serch_requirement':{en: 'Serch Requirement',th:'ค้นหาคำร้องขอ'},
    'attendees':{en:'Attendees',th:'ผู้เข้าร่วมประชุม'},
    'serch_conference_topics':{en:'Serch Conference topics',th:'ค้นหาหัวข้อการประชุม'},
    'requirement_no':{en:'Requirement No',th:'เลขที่คำร้องขอ'},
    'program_support':{en:'Program Support',th:'โปรแกรมรองรับ'},
    'have':{en:'Have',th:'มี'},
    'none':{en:'None',th:'ไม่มี'},
    'download_the_old_file':{en:'Download The Old fFile',th:'ดาวน์โหลดไฟล์เก่า'},
    'approval_information':{ en :'Approval Information', th :'ข้อมูลการอนุมัติ'},
    'requirement_information':{en:'Requirement Information',th:'ข้อมูลคำร้องขอ'},
    'requirement_at_waiting_for_approval':{en:'Requirement At Waiting For Approval',th:'รายการคำร้องขอที่รอการอนุมัติ'},
    'approval_list':{en:'Approval List',th:'รายการการอนุมัติ'},
    'approval_date':{en:'Approval Date',th:'วันที่อนุมัติ'},
    'approvers':{en:'Approvers',th:'ผู้อนุมัติ'},
    'old_file':{en:'Old fFile',th:'ไฟล์เก่า'},
    'work':{en:'Work',th:'งาน'},
    'import_list':{ en :'Import List', th :'รายการการนำเข้าพัฒนา'},
    'approved_requirement':{ en :'Approved Requirement', th :'คำร้องขอที่ได้รับการอนุมัติ'},
    'approval_results':{ en :'Approval Results', th :'ผลการอนุมัติ'},
    'open_task':{ en :'Open Task', th :'เปิดงาน'},
    'task_management':{ en :'Task Management', th :'จัดการงาน'},
    'list_requirement_approve':{en:'A List Of Approved Or Bounced Requests',th:'รายการคำร้องขอที่ได้รับการอนุมัติหรืองานที่ถูกตีกลับ'},
    'easy':{en:'Easy',th:'ง่าย'},
    'medial':{en:'Medial',th:'ปานกลาง'},
    'hard':{en:'Hard',th:'ยาก'},
    'low':{en:'Low',th:'น้อย'},
    'high':{en:'High',th:'มาก'},
    'task_list':{en:'Task List',th:'รายการงาน'},
    'search_task':{en: 'Search Task',th:'ค้นหางาน'},
    'data_can_not_delete':{en: 'Data Can Not Be Deleted',th:'ไม่สามารถลบข้อมูลได้'},
    'data_status_can_not_delete':{en: 'Data Has A Status That Can Not Be Deleted',th:'ข้อมูลมีสถานะไม่สามารถลบข้อมูลได้'},
    'planned_task_list':{en: 'Planned Task List',th:'รายการงานที่วางแผนแล้ว'},
    'employee_list':{en: 'Employee List',th:'รายชื่อพนักงาน'},
    'employee_data':{en:'Employeedata Information',th:'ข้อมูลพนักงาน'},
    'task_list_doing':{en:'Task List Doing',th:'รายการงานที่กำลังพัฒนา'},
    'past' : {en : 'Past',th :'ผ่าน'},
    'fail' : {en : 'Fail',th :'ไม่ผ่าน'},
    'consideration' : {en : 'Consideration',th :'การพิจารณา'},
    'information_considered' : {en : 'Information Considered',th :'ข้อมูลการพิจารณา'},
    'search_testing' : {en : 'Search testing',th : 'ค้นหาการทดสอบ'},
    'data_min_0' : {en : 'Data Must Be An Integer Greater Than 0',th : 'ข้อมูลต้องเป็นจำนวนเต็มที่มีค่ามากกว่า 0'},
    'data_min_1' : {en : 'Data Must Be An Integer Greater Than Or Equal To 0',th : 'ข้อมูลต้องเป็นจำนวนเต็มที่มีค่ามากกว่าหรือเท่ากับ 0'},
    'duplicate' : {en : 'Duplicate',th : 'ข้อมูลซ้ำ'},
    'open_task_information' : {en : 'Open Task Information',th : 'ข้อมูลการเปิดงาน'},
    'error_information' : {en : 'Error Information',th : 'ข้อมูลผิดพลาด'},
    'consideration_list' : {en : 'Consideration List',th : 'รายการการพิจารณา'},
    'developmental_information' : {en : 'Developmental Information',th :'ข้อมูลการพัฒนา'},
    'report' : {en : 'Report',th :'รายงาน'},
    'employee_performance' : {en : 'Employee Performance',th :'ผลการทำงานของพนักงาน'},
    'employee_performance_report' : {en : 'Employee Performance Report',th :'รายงานผลการทำงานของพนักงาน'},
    'condition_searching' : {en : 'Condition Searching',th :'เงื่อนไขการค้นหา'},
    'duration' : {en : 'Duration',th :'ช่วงเวลา'},
    'to' : {en : 'To',th :'ถึง'},
    'search' : {en : 'Search',th : 'ค้นหา'},
    'total_task' : {en : 'Total Task',th : 'งานทั้งหมด'},
    'reject_task' : {en : 'Reject Task',th : 'งานที่ถูกตีกลับ'},
    'finished_task' : {en : 'Finished Task',th : 'งานที่เสร็จสิ้น'},
    'process_task' : {en : 'Process Task',th : 'งานที่กำลังดำเนินการ'},
    'export_to_pdf' : {en : 'Export To PDF',th : 'ส่งออกเป็น PDF'},
    'print' : {en : 'Print',th : 'พิมพ์'},
    'report_task' : {en : 'Report Task By Period',th : 'รายงานงานตามช่วงเวลา'},
    'report_track' : {en : 'Report Track',th : 'รายงานการติดตามแผนงาน'},
    'testing_list' : {en : 'Testing list', th : 'รายการการทดสอบ'},
    'requirement_list':{ en :'Requirement list', th :'รายการคำร้องขอ'},
    'employee_list':{ en :'Employee list', th :'รายการข้อมูลพนักงาน'},
    'position_list' :{en:'Position list',th :'รายการตำแหน่ง'},
    'department_list':{ en :'Department list', th :'รายการฝ่าย'},
    'division_list':{ en :'Division list', th :'รายการแผนก'},
    'business_type_list':{en :'Business type list',th :'รายการประเภทธุรกิจ'},
    'company_list':{ en :'Company list', th :'รายการข้อมูลบริษัท'},
    'tracing':{ en :'Tracing', th :'การติดตาม'},
    'slower_than_planned':{ en :'Slower Than Planned', th :'ช้ากว่าแผน'},
    'as_plan':{ en :'As Plan', th :'ตามแผน'},
    'not_yet_developed':{ en :'Not Yet Developed', th :'ยังไม่ได้พัฒนา'},
    'report_requirement':{ en :'Report Requirement', th :'รายงานคำร้องขอ'},
    'all_requirement':{ en :'All Requirement', th :'คำร้องขอทั้งหมด'},
    'proceed':{ en :'Proceed', th :'กำลังดำเนินการ'},
    'finish':{ en :'Finish', th :'เสร็จสิ้น'},
    'close':{ en :'Close', th :'ปิด'},
    'tasl_list_of':{ en :'Task List Of', th :'รายการงานของ'},
    'requirement_list_of':{ en :'Requirement List Of', th :'รายการคำร้องขอของ'},
}

module.exports = lang
    